import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";

//components
import Navbar from "./components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travel Ease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="font-extrabold text-center text-4xl text-yellow-500 p-10 bg-blue-600">
          ✈️Travel Ease🌴
        </h1>
        <Navbar />
        {children}
      </body>
    </html>
  );
}