import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";

//components
import Navbar from "./components/Navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travel Ease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href={"/"}>
          <h1
            className={`${inter.className} antialiased font-extrabold text-center text-xl text-black p-2 bg-white`}
          >
            ✈️Travel Ease🌴
          </h1>
        </Link>
        <Navbar />
        {children}
      </body>
    </html>
  );
}